# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QWidget)

class WidgetAuditorio(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(859, 545)
        Widget.setMinimumSize(QSize(859, 545))
        Widget.setMaximumSize(QSize(859, 545))
        self.widget_class_meeting_02 = QWidget(Widget)
        self.widget_class_meeting_02.setObjectName(u"widget_class_meeting_02")
        self.widget_class_meeting_02.setGeometry(QRect(500, 150, 269, 192))
        self.subtitle_class_meeting_3 = QLabel(self.widget_class_meeting_02)
        self.subtitle_class_meeting_3.setObjectName(u"subtitle_class_meeting_3")
        self.subtitle_class_meeting_3.setGeometry(QRect(0, 0, 87, 18))
        font = QFont()
        font.setFamilies([u"Versa Versa"])
        font.setPointSize(11)
        self.subtitle_class_meeting_3.setFont(font)
        self.pushButton_reserve_class_meeting_3 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_reserve_class_meeting_3.setObjectName(u"pushButton_reserve_class_meeting_3")
        self.pushButton_reserve_class_meeting_3.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_3 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_delete_class_meeting_3.setObjectName(u"pushButton_delete_class_meeting_3")
        self.pushButton_delete_class_meeting_3.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_3 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_edit_class_meeting_3.setObjectName(u"pushButton_edit_class_meeting_3")
        self.pushButton_edit_class_meeting_3.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_3 = QLabel(self.widget_class_meeting_02)
        self.label_description_class_meeting_3.setObjectName(u"label_description_class_meeting_3")
        self.label_description_class_meeting_3.setGeometry(QRect(10, 40, 241, 91))
        font1 = QFont()
        font1.setFamilies([u"Versa Versa"])
        font1.setPointSize(12)
        self.label_description_class_meeting_3.setFont(font1)
        self.label_description_class_meeting_3.setStyleSheet(u"")
        self.label_description_class_meeting_3.setScaledContents(False)
        self.label_description_class_meeting_3.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_3.setWordWrap(True)
        self.widget_class_meeting_04 = QWidget(Widget)
        self.widget_class_meeting_04.setObjectName(u"widget_class_meeting_04")
        self.widget_class_meeting_04.setGeometry(QRect(500, 360, 269, 191))
        self.subtitle_class_meeting_5 = QLabel(self.widget_class_meeting_04)
        self.subtitle_class_meeting_5.setObjectName(u"subtitle_class_meeting_5")
        self.subtitle_class_meeting_5.setGeometry(QRect(0, 0, 106, 18))
        self.subtitle_class_meeting_5.setFont(font)
        self.pushButton_reserve_class_meeting_5 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_reserve_class_meeting_5.setObjectName(u"pushButton_reserve_class_meeting_5")
        self.pushButton_reserve_class_meeting_5.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_5 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_delete_class_meeting_5.setObjectName(u"pushButton_delete_class_meeting_5")
        self.pushButton_delete_class_meeting_5.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_5 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_edit_class_meeting_5.setObjectName(u"pushButton_edit_class_meeting_5")
        self.pushButton_edit_class_meeting_5.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_5 = QLabel(self.widget_class_meeting_04)
        self.label_description_class_meeting_5.setObjectName(u"label_description_class_meeting_5")
        self.label_description_class_meeting_5.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_5.setFont(font1)
        self.label_description_class_meeting_5.setStyleSheet(u"")
        self.label_description_class_meeting_5.setScaledContents(False)
        self.label_description_class_meeting_5.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_5.setWordWrap(True)
        self.horizontalFrame_3 = QFrame(Widget)
        self.horizontalFrame_3.setObjectName(u"horizontalFrame_3")
        self.horizontalFrame_3.setGeometry(QRect(70, 80, 731, 51))
        self.horizontalFrame_3.setFrameShape(QFrame.Box)
        self.horizontalFrame_3.setFrameShadow(QFrame.Sunken)
        self.horizontalLayout_13 = QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.subtitle_environments_meeting_2 = QLabel(self.horizontalFrame_3)
        self.subtitle_environments_meeting_2.setObjectName(u"subtitle_environments_meeting_2")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitle_environments_meeting_2.sizePolicy().hasHeightForWidth())
        self.subtitle_environments_meeting_2.setSizePolicy(sizePolicy)
        self.subtitle_environments_meeting_2.setMaximumSize(QSize(16777215, 25))
        font2 = QFont()
        font2.setFamilies([u"Versa Versa"])
        font2.setPointSize(18)
        self.subtitle_environments_meeting_2.setFont(font2)
        self.subtitle_environments_meeting_2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_13.addWidget(self.subtitle_environments_meeting_2)

        self.pushButton_adicionar_salaestudo_2 = QPushButton(self.horizontalFrame_3)
        self.pushButton_adicionar_salaestudo_2.setObjectName(u"pushButton_adicionar_salaestudo_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_adicionar_salaestudo_2.sizePolicy().hasHeightForWidth())
        self.pushButton_adicionar_salaestudo_2.setSizePolicy(sizePolicy1)
        self.pushButton_adicionar_salaestudo_2.setMaximumSize(QSize(25, 25))
        self.pushButton_adicionar_salaestudo_2.setFont(font2)
        self.pushButton_adicionar_salaestudo_2.setAutoDefault(False)
        self.pushButton_adicionar_salaestudo_2.setFlat(False)

        self.horizontalLayout_13.addWidget(self.pushButton_adicionar_salaestudo_2)

        self.label_14 = QLabel(self.horizontalFrame_3)
        self.label_14.setObjectName(u"label_14")
        sizePolicy1.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy1)

        self.horizontalLayout_13.addWidget(self.label_14)

        self.footer_frame_auditorium = QFrame(Widget)
        self.footer_frame_auditorium.setObjectName(u"footer_frame_auditorium")
        self.footer_frame_auditorium.setGeometry(QRect(110, 520, 661, 26))
        self.footer_frame_auditorium.setFrameShape(QFrame.NoFrame)
        self.footer_frame_auditorium.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.footer_frame_auditorium)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(10, 2, 2, 2)
        self.footer_icon_facebook_2 = QLabel(self.footer_frame_auditorium)
        self.footer_icon_facebook_2.setObjectName(u"footer_icon_facebook_2")
        self.footer_icon_facebook_2.setMaximumSize(QSize(20, 20))
        self.footer_icon_facebook_2.setPixmap(QPixmap(u"../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/github.png"))
        self.footer_icon_facebook_2.setScaledContents(True)
        self.footer_icon_facebook_2.setWordWrap(False)

        self.horizontalLayout_2.addWidget(self.footer_icon_facebook_2)

        self.footer_icon_likedin_2 = QLabel(self.footer_frame_auditorium)
        self.footer_icon_likedin_2.setObjectName(u"footer_icon_likedin_2")
        self.footer_icon_likedin_2.setMaximumSize(QSize(20, 20))
        self.footer_icon_likedin_2.setPixmap(QPixmap(u"../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/linkedin.png"))
        self.footer_icon_likedin_2.setScaledContents(True)

        self.horizontalLayout_2.addWidget(self.footer_icon_likedin_2)

        self.footer_icon_git_2 = QLabel(self.footer_frame_auditorium)
        self.footer_icon_git_2.setObjectName(u"footer_icon_git_2")
        self.footer_icon_git_2.setMaximumSize(QSize(20, 20))
        self.footer_icon_git_2.setPixmap(QPixmap(u"../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/facebook-app-symbol.png"))
        self.footer_icon_git_2.setScaledContents(True)

        self.horizontalLayout_2.addWidget(self.footer_icon_git_2)

        self.gridFrame = QFrame(Widget)
        self.gridFrame.setObjectName(u"gridFrame")
        self.gridFrame.setGeometry(QRect(65, 10, 741, 61))
        self.gridFrame.setFrameShape(QFrame.Box)
        self.gridFrame.setFrameShadow(QFrame.Raised)
        self.gridFrame.setLineWidth(1)
        self.horizontalLayout_4 = QHBoxLayout(self.gridFrame)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.pushButton_auditorio_voltar = QPushButton(self.gridFrame)
        self.pushButton_auditorio_voltar.setObjectName(u"pushButton_auditorio_voltar")
        sizePolicy1.setHeightForWidth(self.pushButton_auditorio_voltar.sizePolicy().hasHeightForWidth())
        self.pushButton_auditorio_voltar.setSizePolicy(sizePolicy1)
        font3 = QFont()
        font3.setFamilies([u"Versa"])
        font3.setPointSize(10)
        self.pushButton_auditorio_voltar.setFont(font3)
        self.pushButton_auditorio_voltar.setLayoutDirection(Qt.RightToLeft)
        self.pushButton_auditorio_voltar.setFlat(False)

        self.horizontalLayout_4.addWidget(self.pushButton_auditorio_voltar)

        self.label_34 = QLabel(self.gridFrame)
        self.label_34.setObjectName(u"label_34")
        font4 = QFont()
        font4.setFamilies([u"Versa"])
        font4.setPointSize(24)
        font4.setBold(False)
        font4.setItalic(False)
        self.label_34.setFont(font4)
        self.label_34.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)

        self.horizontalLayout_4.addWidget(self.label_34)

        self.widget_class_meeting_01 = QWidget(Widget)
        self.widget_class_meeting_01.setObjectName(u"widget_class_meeting_01")
        self.widget_class_meeting_01.setGeometry(QRect(110, 150, 270, 192))
        self.subtitle_class_meeting_2 = QLabel(self.widget_class_meeting_01)
        self.subtitle_class_meeting_2.setObjectName(u"subtitle_class_meeting_2")
        self.subtitle_class_meeting_2.setGeometry(QRect(0, 0, 86, 18))
        self.subtitle_class_meeting_2.setFont(font)
        self.pushButton_reserve_class_meeting_2 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_reserve_class_meeting_2.setObjectName(u"pushButton_reserve_class_meeting_2")
        self.pushButton_reserve_class_meeting_2.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_2 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_delete_class_meeting_2.setObjectName(u"pushButton_delete_class_meeting_2")
        self.pushButton_delete_class_meeting_2.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_2 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_edit_class_meeting_2.setObjectName(u"pushButton_edit_class_meeting_2")
        self.pushButton_edit_class_meeting_2.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_2 = QLabel(self.widget_class_meeting_01)
        self.label_description_class_meeting_2.setObjectName(u"label_description_class_meeting_2")
        self.label_description_class_meeting_2.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_2.setFont(font1)
        self.label_description_class_meeting_2.setStyleSheet(u"")
        self.label_description_class_meeting_2.setScaledContents(False)
        self.label_description_class_meeting_2.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_2.setWordWrap(True)
        self.widget_class_meeting_03 = QWidget(Widget)
        self.widget_class_meeting_03.setObjectName(u"widget_class_meeting_03")
        self.widget_class_meeting_03.setGeometry(QRect(110, 360, 270, 191))
        self.subtitle_sl_pipa_2 = QLabel(self.widget_class_meeting_03)
        self.subtitle_sl_pipa_2.setObjectName(u"subtitle_sl_pipa_2")
        self.subtitle_sl_pipa_2.setGeometry(QRect(0, 0, 75, 18))
        self.subtitle_sl_pipa_2.setFont(font)
        self.pushButton_reserve_class_meeting_4 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_reserve_class_meeting_4.setObjectName(u"pushButton_reserve_class_meeting_4")
        self.pushButton_reserve_class_meeting_4.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_14 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_4 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_edit_class_meeting_4.setObjectName(u"pushButton_edit_class_meeting_4")
        self.pushButton_edit_class_meeting_4.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_4 = QLabel(self.widget_class_meeting_03)
        self.label_description_class_meeting_4.setObjectName(u"label_description_class_meeting_4")
        self.label_description_class_meeting_4.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_4.setFont(font1)
        self.label_description_class_meeting_4.setStyleSheet(u"")
        self.label_description_class_meeting_4.setScaledContents(False)
        self.label_description_class_meeting_4.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_4.setWordWrap(True)

        self.retranslateUi(Widget)

        self.pushButton_adicionar_salaestudo_2.setDefault(False)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.subtitle_class_meeting_3.setText(QCoreApplication.translate("Widget", u"Sala 02", None))
        self.pushButton_reserve_class_meeting_3.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_3.setText(QCoreApplication.translate("Widget", u"exluir", None))
        self.pushButton_edit_class_meeting_3.setText(QCoreApplication.translate("Widget", u"editar ", None))
        self.label_description_class_meeting_3.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_class_meeting_5.setText(QCoreApplication.translate("Widget", u"sala 04", None))
        self.pushButton_reserve_class_meeting_5.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_5.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_5.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_5.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_environments_meeting_2.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">Auditorio</p></body></html>", None))
        self.pushButton_adicionar_salaestudo_2.setText(QCoreApplication.translate("Widget", u"+", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Adicionar Nova Sala", None))
        self.footer_icon_facebook_2.setText("")
        self.footer_icon_likedin_2.setText("")
        self.footer_icon_git_2.setText("")
        self.pushButton_auditorio_voltar.setText(QCoreApplication.translate("Widget", u"voltar", None))
        self.label_34.setText(QCoreApplication.translate("Widget", u"                           SICOGES", None))
        self.subtitle_class_meeting_2.setText(QCoreApplication.translate("Widget", u"Sala 01", None))
        self.pushButton_reserve_class_meeting_2.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_2.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_2.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_2.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_sl_pipa_2.setText(QCoreApplication.translate("Widget", u"sala 03", None))
        self.pushButton_reserve_class_meeting_4.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_14.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_4.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_4.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
    # retranslateUi

