# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QWidget)

class Laboratorio(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(859, 545)
        Widget.setMinimumSize(QSize(859, 545))
        Widget.setMaximumSize(QSize(859, 545))
        self.widget_lab01 = QWidget(Widget)
        self.widget_lab01.setObjectName(u"widget_lab01")
        self.widget_lab01.setGeometry(QRect(80, 140, 270, 192))
        self.subtitle_lab01 = QLabel(self.widget_lab01)
        self.subtitle_lab01.setObjectName(u"subtitle_lab01")
        self.subtitle_lab01.setGeometry(QRect(0, 0, 86, 18))
        font = QFont()
        font.setFamilies([u"Versa Versa"])
        font.setPointSize(11)
        self.subtitle_lab01.setFont(font)
        self.pushButton_reserve_lab01 = QPushButton(self.widget_lab01)
        self.pushButton_reserve_lab01.setObjectName(u"pushButton_reserve_lab01")
        self.pushButton_reserve_lab01.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_lab01 = QPushButton(self.widget_lab01)
        self.pushButton_delete_lab01.setObjectName(u"pushButton_delete_lab01")
        self.pushButton_delete_lab01.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_lab01 = QPushButton(self.widget_lab01)
        self.pushButton_edit_lab01.setObjectName(u"pushButton_edit_lab01")
        self.pushButton_edit_lab01.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_lab01 = QLabel(self.widget_lab01)
        self.label_description_lab01.setObjectName(u"label_description_lab01")
        self.label_description_lab01.setGeometry(QRect(10, 40, 241, 91))
        font1 = QFont()
        font1.setFamilies([u"Versa Versa"])
        font1.setPointSize(12)
        self.label_description_lab01.setFont(font1)
        self.label_description_lab01.setStyleSheet(u"")
        self.label_description_lab01.setScaledContents(False)
        self.label_description_lab01.setAlignment(Qt.AlignCenter)
        self.label_description_lab01.setWordWrap(True)
        self.gridFrame = QFrame(Widget)
        self.gridFrame.setObjectName(u"gridFrame")
        self.gridFrame.setGeometry(QRect(35, 0, 741, 61))
        self.gridFrame.setFrameShape(QFrame.Box)
        self.gridFrame.setFrameShadow(QFrame.Raised)
        self.gridFrame.setLineWidth(1)
        self.horizontalLayout_3 = QHBoxLayout(self.gridFrame)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.pushButton_lab_voltar = QPushButton(self.gridFrame)
        self.pushButton_lab_voltar.setObjectName(u"pushButton_lab_voltar")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_lab_voltar.sizePolicy().hasHeightForWidth())
        self.pushButton_lab_voltar.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setFamilies([u"Versa"])
        font2.setPointSize(10)
        self.pushButton_lab_voltar.setFont(font2)
        self.pushButton_lab_voltar.setLayoutDirection(Qt.RightToLeft)
        self.pushButton_lab_voltar.setFlat(False)

        self.horizontalLayout_3.addWidget(self.pushButton_lab_voltar)

        self.label_33 = QLabel(self.gridFrame)
        self.label_33.setObjectName(u"label_33")
        font3 = QFont()
        font3.setFamilies([u"Versa"])
        font3.setPointSize(24)
        font3.setBold(False)
        font3.setItalic(False)
        self.label_33.setFont(font3)
        self.label_33.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_33)

        self.widget_lab04 = QWidget(Widget)
        self.widget_lab04.setObjectName(u"widget_lab04")
        self.widget_lab04.setGeometry(QRect(470, 350, 269, 191))
        self.subtitle_lab04 = QLabel(self.widget_lab04)
        self.subtitle_lab04.setObjectName(u"subtitle_lab04")
        self.subtitle_lab04.setGeometry(QRect(0, 0, 106, 18))
        self.subtitle_lab04.setFont(font)
        self.pushButton_reserve_lab04 = QPushButton(self.widget_lab04)
        self.pushButton_reserve_lab04.setObjectName(u"pushButton_reserve_lab04")
        self.pushButton_reserve_lab04.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_lab04 = QPushButton(self.widget_lab04)
        self.pushButton_delete_lab04.setObjectName(u"pushButton_delete_lab04")
        self.pushButton_delete_lab04.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_lab04 = QPushButton(self.widget_lab04)
        self.pushButton_edit_lab04.setObjectName(u"pushButton_edit_lab04")
        self.pushButton_edit_lab04.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_lab04 = QLabel(self.widget_lab04)
        self.label_description_lab04.setObjectName(u"label_description_lab04")
        self.label_description_lab04.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_lab04.setFont(font1)
        self.label_description_lab04.setStyleSheet(u"")
        self.label_description_lab04.setScaledContents(False)
        self.label_description_lab04.setAlignment(Qt.AlignCenter)
        self.label_description_lab04.setWordWrap(True)
        self.horizontalFrame_3 = QFrame(Widget)
        self.horizontalFrame_3.setObjectName(u"horizontalFrame_3")
        self.horizontalFrame_3.setGeometry(QRect(40, 70, 731, 51))
        self.horizontalFrame_3.setFrameShape(QFrame.Box)
        self.horizontalFrame_3.setFrameShadow(QFrame.Sunken)
        self.horizontalLayout_12 = QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.subtitle_lab = QLabel(self.horizontalFrame_3)
        self.subtitle_lab.setObjectName(u"subtitle_lab")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.subtitle_lab.sizePolicy().hasHeightForWidth())
        self.subtitle_lab.setSizePolicy(sizePolicy1)
        self.subtitle_lab.setMaximumSize(QSize(16777215, 25))
        font4 = QFont()
        font4.setFamilies([u"Versa Versa"])
        font4.setPointSize(18)
        self.subtitle_lab.setFont(font4)
        self.subtitle_lab.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_12.addWidget(self.subtitle_lab)

        self.pushButton_adicionar_lab = QPushButton(self.horizontalFrame_3)
        self.pushButton_adicionar_lab.setObjectName(u"pushButton_adicionar_lab")
        sizePolicy.setHeightForWidth(self.pushButton_adicionar_lab.sizePolicy().hasHeightForWidth())
        self.pushButton_adicionar_lab.setSizePolicy(sizePolicy)
        self.pushButton_adicionar_lab.setMaximumSize(QSize(25, 25))
        self.pushButton_adicionar_lab.setFont(font4)
        self.pushButton_adicionar_lab.setAutoDefault(False)
        self.pushButton_adicionar_lab.setFlat(False)

        self.horizontalLayout_12.addWidget(self.pushButton_adicionar_lab)

        self.label_13 = QLabel(self.horizontalFrame_3)
        self.label_13.setObjectName(u"label_13")
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)

        self.horizontalLayout_12.addWidget(self.label_13)

        self.widget_lab03 = QWidget(Widget)
        self.widget_lab03.setObjectName(u"widget_lab03")
        self.widget_lab03.setGeometry(QRect(80, 350, 270, 191))
        self.subtitle_lab03 = QLabel(self.widget_lab03)
        self.subtitle_lab03.setObjectName(u"subtitle_lab03")
        self.subtitle_lab03.setGeometry(QRect(0, 0, 75, 18))
        self.subtitle_lab03.setFont(font)
        self.pushButton_reserve_lab03 = QPushButton(self.widget_lab03)
        self.pushButton_reserve_lab03.setObjectName(u"pushButton_reserve_lab03")
        self.pushButton_reserve_lab03.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_lab03 = QPushButton(self.widget_lab03)
        self.pushButton_delete_lab03.setObjectName(u"pushButton_delete_lab03")
        self.pushButton_delete_lab03.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_lab03 = QPushButton(self.widget_lab03)
        self.pushButton_edit_lab03.setObjectName(u"pushButton_edit_lab03")
        self.pushButton_edit_lab03.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_lab03 = QLabel(self.widget_lab03)
        self.label_description_lab03.setObjectName(u"label_description_lab03")
        self.label_description_lab03.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_lab03.setFont(font1)
        self.label_description_lab03.setStyleSheet(u"")
        self.label_description_lab03.setScaledContents(False)
        self.label_description_lab03.setAlignment(Qt.AlignCenter)
        self.label_description_lab03.setWordWrap(True)
        self.widget_lab02 = QWidget(Widget)
        self.widget_lab02.setObjectName(u"widget_lab02")
        self.widget_lab02.setGeometry(QRect(470, 140, 269, 192))
        self.subtitle_lab02 = QLabel(self.widget_lab02)
        self.subtitle_lab02.setObjectName(u"subtitle_lab02")
        self.subtitle_lab02.setGeometry(QRect(0, 0, 87, 18))
        self.subtitle_lab02.setFont(font)
        self.pushButton_reserve_lab02 = QPushButton(self.widget_lab02)
        self.pushButton_reserve_lab02.setObjectName(u"pushButton_reserve_lab02")
        self.pushButton_reserve_lab02.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_lab02 = QPushButton(self.widget_lab02)
        self.pushButton_delete_lab02.setObjectName(u"pushButton_delete_lab02")
        self.pushButton_delete_lab02.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_lab02 = QPushButton(self.widget_lab02)
        self.pushButton_edit_lab02.setObjectName(u"pushButton_edit_lab02")
        self.pushButton_edit_lab02.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_lab02 = QLabel(self.widget_lab02)
        self.label_description_lab02.setObjectName(u"label_description_lab02")
        self.label_description_lab02.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_lab02.setFont(font1)
        self.label_description_lab02.setStyleSheet(u"")
        self.label_description_lab02.setScaledContents(False)
        self.label_description_lab02.setAlignment(Qt.AlignCenter)
        self.label_description_lab02.setWordWrap(True)
        self.footer_frame_auditorium_3 = QFrame(Widget)
        self.footer_frame_auditorium_3.setObjectName(u"footer_frame_auditorium_3")
        self.footer_frame_auditorium_3.setGeometry(QRect(80, 510, 661, 26))
        self.footer_frame_auditorium_3.setFrameShape(QFrame.NoFrame)
        self.footer_frame_auditorium_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.footer_frame_auditorium_3)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(10, 2, 2, 2)
        self.footer_icon_facebook_3 = QLabel(self.footer_frame_auditorium_3)
        self.footer_icon_facebook_3.setObjectName(u"footer_icon_facebook_3")
        self.footer_icon_facebook_3.setMaximumSize(QSize(20, 20))
        self.footer_icon_facebook_3.setPixmap(QPixmap(u"../../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/github.png"))
        self.footer_icon_facebook_3.setScaledContents(True)
        self.footer_icon_facebook_3.setWordWrap(False)

        self.horizontalLayout_4.addWidget(self.footer_icon_facebook_3)

        self.footer_icon_likedin_3 = QLabel(self.footer_frame_auditorium_3)
        self.footer_icon_likedin_3.setObjectName(u"footer_icon_likedin_3")
        self.footer_icon_likedin_3.setMaximumSize(QSize(20, 20))
        self.footer_icon_likedin_3.setPixmap(QPixmap(u"../../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/linkedin.png"))
        self.footer_icon_likedin_3.setScaledContents(True)

        self.horizontalLayout_4.addWidget(self.footer_icon_likedin_3)

        self.footer_icon_git_3 = QLabel(self.footer_frame_auditorium_3)
        self.footer_icon_git_3.setObjectName(u"footer_icon_git_3")
        self.footer_icon_git_3.setMaximumSize(QSize(20, 20))
        self.footer_icon_git_3.setPixmap(QPixmap(u"../../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/facebook-app-symbol.png"))
        self.footer_icon_git_3.setScaledContents(True)

        self.horizontalLayout_4.addWidget(self.footer_icon_git_3)


        self.retranslateUi(Widget)

        self.pushButton_adicionar_lab.setDefault(False)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.subtitle_lab01.setText(QCoreApplication.translate("Widget", u"Lab 01", None))
        self.pushButton_reserve_lab01.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_lab01.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_lab01.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_lab01.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.pushButton_lab_voltar.setText(QCoreApplication.translate("Widget", u"voltar", None))
        self.label_33.setText(QCoreApplication.translate("Widget", u"                           SICOGES", None))
        self.subtitle_lab04.setText(QCoreApplication.translate("Widget", u"lab 04", None))
        self.pushButton_reserve_lab04.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_lab04.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_lab04.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_lab04.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_lab.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">Laborat\u00f3rios</p></body></html>", None))
        self.pushButton_adicionar_lab.setText(QCoreApplication.translate("Widget", u"+", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Adicionar Nova Sala", None))
        self.subtitle_lab03.setText(QCoreApplication.translate("Widget", u"lab 03", None))
        self.pushButton_reserve_lab03.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_lab03.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_lab03.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_lab03.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_lab02.setText(QCoreApplication.translate("Widget", u"lab 02", None))
        self.pushButton_reserve_lab02.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_lab02.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_lab02.setText(QCoreApplication.translate("Widget", u"editar ", None))
        self.label_description_lab02.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.footer_icon_facebook_3.setText("")
        self.footer_icon_likedin_3.setText("")
        self.footer_icon_git_3.setText("")
    # retranslateUi

