# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QWidget)

class WidgetLaboratorio(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(859, 545)
        Widget.setMinimumSize(QSize(859, 545))
        Widget.setMaximumSize(QSize(859, 545))
        self.widget_class_meeting_04 = QWidget(Widget)
        self.widget_class_meeting_04.setObjectName(u"widget_class_meeting_04")
        self.widget_class_meeting_04.setGeometry(QRect(440, 360, 269, 191))
        self.subtitle_class_meeting_04 = QLabel(self.widget_class_meeting_04)
        self.subtitle_class_meeting_04.setObjectName(u"subtitle_class_meeting_04")
        self.subtitle_class_meeting_04.setGeometry(QRect(0, 0, 106, 18))
        font = QFont()
        font.setFamilies([u"Versa Versa"])
        font.setPointSize(11)
        self.subtitle_class_meeting_04.setFont(font)
        self.pushButton_reserve_class_meeting_04 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_reserve_class_meeting_04.setObjectName(u"pushButton_reserve_class_meeting_04")
        self.pushButton_reserve_class_meeting_04.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_04 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_delete_class_meeting_04.setObjectName(u"pushButton_delete_class_meeting_04")
        self.pushButton_delete_class_meeting_04.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_04 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_edit_class_meeting_04.setObjectName(u"pushButton_edit_class_meeting_04")
        self.pushButton_edit_class_meeting_04.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_04 = QLabel(self.widget_class_meeting_04)
        self.label_description_class_meeting_04.setObjectName(u"label_description_class_meeting_04")
        self.label_description_class_meeting_04.setGeometry(QRect(10, 40, 241, 91))
        font1 = QFont()
        font1.setFamilies([u"Versa Versa"])
        font1.setPointSize(12)
        self.label_description_class_meeting_04.setFont(font1)
        self.label_description_class_meeting_04.setStyleSheet(u"")
        self.label_description_class_meeting_04.setScaledContents(False)
        self.label_description_class_meeting_04.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_04.setWordWrap(True)
        self.subtitle_environments_meeting = QLabel(Widget)
        self.subtitle_environments_meeting.setObjectName(u"subtitle_environments_meeting")
        self.subtitle_environments_meeting.setGeometry(QRect(150, 110, 545, 25))
        self.subtitle_environments_meeting.setMaximumSize(QSize(16777215, 25))
        font2 = QFont()
        font2.setFamilies([u"Versa Versa"])
        font2.setPointSize(18)
        self.subtitle_environments_meeting.setFont(font2)
        self.title_sicoges_auditorium = QLabel(Widget)
        self.title_sicoges_auditorium.setObjectName(u"title_sicoges_auditorium")
        self.title_sicoges_auditorium.setGeometry(QRect(130, 50, 561, 50))
        self.title_sicoges_auditorium.setMaximumSize(QSize(16777215, 50))
        font3 = QFont()
        font3.setFamilies([u"Versa Versa"])
        font3.setPointSize(24)
        self.title_sicoges_auditorium.setFont(font3)
        self.widget_class_meeting_02 = QWidget(Widget)
        self.widget_class_meeting_02.setObjectName(u"widget_class_meeting_02")
        self.widget_class_meeting_02.setGeometry(QRect(440, 160, 269, 192))
        self.subtitle_class_meeting_02 = QLabel(self.widget_class_meeting_02)
        self.subtitle_class_meeting_02.setObjectName(u"subtitle_class_meeting_02")
        self.subtitle_class_meeting_02.setGeometry(QRect(0, 0, 87, 18))
        self.subtitle_class_meeting_02.setFont(font)
        self.pushButton_reserve_class_meeting_02 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_reserve_class_meeting_02.setObjectName(u"pushButton_reserve_class_meeting_02")
        self.pushButton_reserve_class_meeting_02.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_02 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_delete_class_meeting_02.setObjectName(u"pushButton_delete_class_meeting_02")
        self.pushButton_delete_class_meeting_02.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_02 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_edit_class_meeting_02.setObjectName(u"pushButton_edit_class_meeting_02")
        self.pushButton_edit_class_meeting_02.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_02 = QLabel(self.widget_class_meeting_02)
        self.label_description_class_meeting_02.setObjectName(u"label_description_class_meeting_02")
        self.label_description_class_meeting_02.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_02.setFont(font1)
        self.label_description_class_meeting_02.setStyleSheet(u"")
        self.label_description_class_meeting_02.setScaledContents(False)
        self.label_description_class_meeting_02.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_02.setWordWrap(True)
        self.widget_class_meeting_01 = QWidget(Widget)
        self.widget_class_meeting_01.setObjectName(u"widget_class_meeting_01")
        self.widget_class_meeting_01.setGeometry(QRect(50, 160, 270, 192))
        self.subtitle_class_meeting_01 = QLabel(self.widget_class_meeting_01)
        self.subtitle_class_meeting_01.setObjectName(u"subtitle_class_meeting_01")
        self.subtitle_class_meeting_01.setGeometry(QRect(0, 0, 86, 18))
        self.subtitle_class_meeting_01.setFont(font)
        self.pushButton_reserve_class_meeting_01 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_reserve_class_meeting_01.setObjectName(u"pushButton_reserve_class_meeting_01")
        self.pushButton_reserve_class_meeting_01.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_01 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_delete_class_meeting_01.setObjectName(u"pushButton_delete_class_meeting_01")
        self.pushButton_delete_class_meeting_01.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_01 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_edit_class_meeting_01.setObjectName(u"pushButton_edit_class_meeting_01")
        self.pushButton_edit_class_meeting_01.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_01 = QLabel(self.widget_class_meeting_01)
        self.label_description_class_meeting_01.setObjectName(u"label_description_class_meeting_01")
        self.label_description_class_meeting_01.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_01.setFont(font1)
        self.label_description_class_meeting_01.setStyleSheet(u"")
        self.label_description_class_meeting_01.setScaledContents(False)
        self.label_description_class_meeting_01.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_01.setWordWrap(True)
        self.widget_class_meeting_03 = QWidget(Widget)
        self.widget_class_meeting_03.setObjectName(u"widget_class_meeting_03")
        self.widget_class_meeting_03.setGeometry(QRect(50, 360, 270, 191))
        self.subtitle_sl_pipa = QLabel(self.widget_class_meeting_03)
        self.subtitle_sl_pipa.setObjectName(u"subtitle_sl_pipa")
        self.subtitle_sl_pipa.setGeometry(QRect(0, 0, 75, 18))
        self.subtitle_sl_pipa.setFont(font)
        self.pushButton_reserve_class_meeting_03 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_reserve_class_meeting_03.setObjectName(u"pushButton_reserve_class_meeting_03")
        self.pushButton_reserve_class_meeting_03.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_13 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_03 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_edit_class_meeting_03.setObjectName(u"pushButton_edit_class_meeting_03")
        self.pushButton_edit_class_meeting_03.setGeometry(QRect(180, 140, 75, 24))
        self.label_7 = QLabel(self.widget_class_meeting_03)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 40, 241, 91))
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"")
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.footer_frame_auditorium = QFrame(Widget)
        self.footer_frame_auditorium.setObjectName(u"footer_frame_auditorium")
        self.footer_frame_auditorium.setGeometry(QRect(50, 560, 661, 26))
        self.footer_frame_auditorium.setFrameShape(QFrame.NoFrame)
        self.footer_frame_auditorium.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.footer_frame_auditorium)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(10, 2, 2, 2)
        self.footer_icon_facebook = QLabel(self.footer_frame_auditorium)
        self.footer_icon_facebook.setObjectName(u"footer_icon_facebook")
        self.footer_icon_facebook.setMaximumSize(QSize(20, 20))
        self.footer_icon_facebook.setPixmap(QPixmap(u"../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/github.png"))
        self.footer_icon_facebook.setScaledContents(True)
        self.footer_icon_facebook.setWordWrap(False)

        self.horizontalLayout.addWidget(self.footer_icon_facebook)

        self.footer_icon_likedin = QLabel(self.footer_frame_auditorium)
        self.footer_icon_likedin.setObjectName(u"footer_icon_likedin")
        self.footer_icon_likedin.setMaximumSize(QSize(20, 20))
        self.footer_icon_likedin.setPixmap(QPixmap(u"../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/linkedin.png"))
        self.footer_icon_likedin.setScaledContents(True)

        self.horizontalLayout.addWidget(self.footer_icon_likedin)

        self.footer_icon_git = QLabel(self.footer_frame_auditorium)
        self.footer_icon_git.setObjectName(u"footer_icon_git")
        self.footer_icon_git.setMaximumSize(QSize(20, 20))
        self.footer_icon_git.setPixmap(QPixmap(u"../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/facebook-app-symbol.png"))
        self.footer_icon_git.setScaledContents(True)

        self.horizontalLayout.addWidget(self.footer_icon_git)


        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.subtitle_class_meeting_04.setText(QCoreApplication.translate("Widget", u"sala 04", None))
        self.pushButton_reserve_class_meeting_04.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_04.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_04.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_04.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">34m\u00b2 com capacidade para 20 pessoas</span></p><p><span style=\" font-size:11pt;\"><br/></span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>", None))
        self.subtitle_environments_meeting.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">salas de reuni\u00e3o</p><p align=\"center\"><br/></p></body></html>", None))
        self.title_sicoges_auditorium.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">SICOGES</p><p align=\"center\"><br/></p></body></html>", None))
        self.subtitle_class_meeting_02.setText(QCoreApplication.translate("Widget", u"Sala 02", None))
        self.pushButton_reserve_class_meeting_02.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_02.setText(QCoreApplication.translate("Widget", u"exluir", None))
        self.pushButton_edit_class_meeting_02.setText(QCoreApplication.translate("Widget", u"editar ", None))
        self.label_description_class_meeting_02.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">37m\u00b2 com capacidade para 25 pessoas</span></p><p><span style=\" font-size:11pt;\"><br/></span></p><p><span style=\" font-size:11pt;\"><br/></span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>", None))
        self.subtitle_class_meeting_01.setText(QCoreApplication.translate("Widget", u"Sala 01", None))
        self.pushButton_reserve_class_meeting_01.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_01.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_01.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_01.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">54m\u00b2 com campacidade para 45 pessoas</span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>", None))
        self.subtitle_sl_pipa.setText(QCoreApplication.translate("Widget", u"sala 03", None))
        self.pushButton_reserve_class_meeting_03.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_13.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_03.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">43m\u00b2 com capacidade para 30 pessoas</span></p><p><span style=\" font-size:11pt;\"><br/></span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>", None))
        self.footer_icon_facebook.setText("")
        self.footer_icon_likedin.setText("")
        self.footer_icon_git.setText("")
    # retranslateUi

