# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QWidget)

class Sala_de_estudo(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(759, 542)
        self.footer_frame_auditorium = QFrame(Widget)
        self.footer_frame_auditorium.setObjectName(u"footer_frame_auditorium")
        self.footer_frame_auditorium.setGeometry(QRect(50, 520, 661, 26))
        self.footer_frame_auditorium.setFrameShape(QFrame.NoFrame)
        self.footer_frame_auditorium.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.footer_frame_auditorium)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(10, 2, 2, 2)
        self.footer_icon_facebook = QLabel(self.footer_frame_auditorium)
        self.footer_icon_facebook.setObjectName(u"footer_icon_facebook")
        self.footer_icon_facebook.setMaximumSize(QSize(20, 20))
        self.footer_icon_facebook.setPixmap(QPixmap(u"../../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/github.png"))
        self.footer_icon_facebook.setScaledContents(True)
        self.footer_icon_facebook.setWordWrap(False)

        self.horizontalLayout.addWidget(self.footer_icon_facebook)

        self.footer_icon_likedin = QLabel(self.footer_frame_auditorium)
        self.footer_icon_likedin.setObjectName(u"footer_icon_likedin")
        self.footer_icon_likedin.setMaximumSize(QSize(20, 20))
        self.footer_icon_likedin.setPixmap(QPixmap(u"../../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/linkedin.png"))
        self.footer_icon_likedin.setScaledContents(True)

        self.horizontalLayout.addWidget(self.footer_icon_likedin)

        self.footer_icon_git = QLabel(self.footer_frame_auditorium)
        self.footer_icon_git.setObjectName(u"footer_icon_git")
        self.footer_icon_git.setMaximumSize(QSize(20, 20))
        self.footer_icon_git.setPixmap(QPixmap(u"../../../../../layzacecato-dev_my_projects/github/reposity06_poo_2_bim/controle-salas/ambientes/icons/facebook-app-symbol.png"))
        self.footer_icon_git.setScaledContents(True)

        self.horizontalLayout.addWidget(self.footer_icon_git)

        self.widget_class_meeting_02 = QWidget(Widget)
        self.widget_class_meeting_02.setObjectName(u"widget_class_meeting_02")
        self.widget_class_meeting_02.setGeometry(QRect(440, 150, 269, 192))
        self.subtitle_class_meeting_02 = QLabel(self.widget_class_meeting_02)
        self.subtitle_class_meeting_02.setObjectName(u"subtitle_class_meeting_02")
        self.subtitle_class_meeting_02.setGeometry(QRect(0, 0, 87, 18))
        font = QFont()
        font.setFamilies([u"Versa Versa"])
        font.setPointSize(11)
        self.subtitle_class_meeting_02.setFont(font)
        self.pushButton_reserve_class_meeting_02 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_reserve_class_meeting_02.setObjectName(u"pushButton_reserve_class_meeting_02")
        self.pushButton_reserve_class_meeting_02.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_02 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_delete_class_meeting_02.setObjectName(u"pushButton_delete_class_meeting_02")
        self.pushButton_delete_class_meeting_02.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_02 = QPushButton(self.widget_class_meeting_02)
        self.pushButton_edit_class_meeting_02.setObjectName(u"pushButton_edit_class_meeting_02")
        self.pushButton_edit_class_meeting_02.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_02 = QLabel(self.widget_class_meeting_02)
        self.label_description_class_meeting_02.setObjectName(u"label_description_class_meeting_02")
        self.label_description_class_meeting_02.setGeometry(QRect(10, 40, 241, 91))
        font1 = QFont()
        font1.setFamilies([u"Versa Versa"])
        font1.setPointSize(12)
        self.label_description_class_meeting_02.setFont(font1)
        self.label_description_class_meeting_02.setStyleSheet(u"")
        self.label_description_class_meeting_02.setScaledContents(False)
        self.label_description_class_meeting_02.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_02.setWordWrap(True)
        self.widget_class_meeting_03 = QWidget(Widget)
        self.widget_class_meeting_03.setObjectName(u"widget_class_meeting_03")
        self.widget_class_meeting_03.setGeometry(QRect(50, 360, 270, 191))
        self.subtitle_sl_pipa = QLabel(self.widget_class_meeting_03)
        self.subtitle_sl_pipa.setObjectName(u"subtitle_sl_pipa")
        self.subtitle_sl_pipa.setGeometry(QRect(0, 0, 75, 18))
        self.subtitle_sl_pipa.setFont(font)
        self.pushButton_reserve_class_meeting_03 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_reserve_class_meeting_03.setObjectName(u"pushButton_reserve_meeting_03")
        self.pushButton_reserve_class_meeting_03.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_03 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_delete_class_meeting_03.setObjectName(u"pushButton_delete_class_meeting_03")
        self.pushButton_delete_class_meeting_03.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_03 = QPushButton(self.widget_class_meeting_03)
        self.pushButton_edit_class_meeting_03.setObjectName(u"pushButton_14")
        self.pushButton_edit_class_meeting_03.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_03 = QLabel(self.widget_class_meeting_03)
        self.label_description_class_meeting_03.setObjectName(u"label_7")
        self.label_description_class_meeting_03.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_03.setFont(font1)
        self.label_description_class_meeting_03.setStyleSheet(u"")
        self.label_description_class_meeting_03.setScaledContents(False)
        self.label_description_class_meeting_03.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_03.setWordWrap(True)
        self.widget_class_meeting_01 = QWidget(Widget)
        self.widget_class_meeting_01.setObjectName(u"widget_class_meeting_01")
        self.widget_class_meeting_01.setGeometry(QRect(50, 150, 270, 192))
        self.subtitle_class_meeting_01 = QLabel(self.widget_class_meeting_01)
        self.subtitle_class_meeting_01.setObjectName(u"subtitle_class_meeting_01")
        self.subtitle_class_meeting_01.setGeometry(QRect(0, 0, 86, 18))
        self.subtitle_class_meeting_01.setFont(font)
        self.pushButton_reserve_class_meeting_01 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_reserve_class_meeting_01.setObjectName(u"pushButton_reserve_class_meeting_01")
        self.pushButton_reserve_class_meeting_01.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_01 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_delete_class_meeting_01.setObjectName(u"pushButton_delete_class_meeting_01")
        self.pushButton_delete_class_meeting_01.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_01 = QPushButton(self.widget_class_meeting_01)
        self.pushButton_edit_class_meeting_01.setObjectName(u"pushButton_edit_class_meeting_01")
        self.pushButton_edit_class_meeting_01.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_01 = QLabel(self.widget_class_meeting_01)
        self.label_description_class_meeting_01.setObjectName(u"label_description_class_meeting_01")
        self.label_description_class_meeting_01.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_01.setFont(font1)
        self.label_description_class_meeting_01.setStyleSheet(u"")
        self.label_description_class_meeting_01.setScaledContents(False)
        self.label_description_class_meeting_01.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_01.setWordWrap(True)
        self.widget_class_meeting_04 = QWidget(Widget)
        self.widget_class_meeting_04.setObjectName(u"widget_class_meeting_04")
        self.widget_class_meeting_04.setGeometry(QRect(440, 360, 269, 191))
        self.subtitle_class_meeting_04 = QLabel(self.widget_class_meeting_04)
        self.subtitle_class_meeting_04.setObjectName(u"subtitle_class_meeting_04")
        self.subtitle_class_meeting_04.setGeometry(QRect(0, 0, 106, 18))
        self.subtitle_class_meeting_04.setFont(font)
        self.pushButton_reserve_class_meeting_04 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_reserve_class_meeting_04.setObjectName(u"pushButton_reserve_class_meeting_04")
        self.pushButton_reserve_class_meeting_04.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_delete_class_meeting_04 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_delete_class_meeting_04.setObjectName(u"pushButton_delete_class_meeting_04")
        self.pushButton_delete_class_meeting_04.setGeometry(QRect(95, 140, 75, 24))
        self.pushButton_edit_class_meeting_04 = QPushButton(self.widget_class_meeting_04)
        self.pushButton_edit_class_meeting_04.setObjectName(u"pushButton_edit_class_meeting_04")
        self.pushButton_edit_class_meeting_04.setGeometry(QRect(180, 140, 75, 24))
        self.label_description_class_meeting_04 = QLabel(self.widget_class_meeting_04)
        self.label_description_class_meeting_04.setObjectName(u"label_description_class_meeting_04")
        self.label_description_class_meeting_04.setGeometry(QRect(10, 40, 241, 91))
        self.label_description_class_meeting_04.setFont(font1)
        self.label_description_class_meeting_04.setStyleSheet(u"")
        self.label_description_class_meeting_04.setScaledContents(False)
        self.label_description_class_meeting_04.setAlignment(Qt.AlignCenter)
        self.label_description_class_meeting_04.setWordWrap(True)
        self.gridFrame = QFrame(Widget)
        self.gridFrame.setObjectName(u"gridFrame")
        self.gridFrame.setGeometry(QRect(5, 10, 741, 61))
        self.gridFrame.setFrameShape(QFrame.Box)
        self.gridFrame.setFrameShadow(QFrame.Raised)
        self.gridFrame.setLineWidth(1)
        self.horizontalLayout_3 = QHBoxLayout(self.gridFrame)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.pushButton_salaestudo_voltar = QPushButton(self.gridFrame)
        self.pushButton_salaestudo_voltar.setObjectName(u"pushButton_salaestudo_voltar")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_salaestudo_voltar.sizePolicy().hasHeightForWidth())
        self.pushButton_salaestudo_voltar.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setFamilies([u"Versa"])
        font2.setPointSize(10)
        self.pushButton_salaestudo_voltar.setFont(font2)
        self.pushButton_salaestudo_voltar.setLayoutDirection(Qt.RightToLeft)
        icon = QIcon()
        iconThemeName = u"go-previous"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u"../", QSize(), QIcon.Normal, QIcon.Off)

        self.pushButton_salaestudo_voltar.setIcon(icon)
        self.pushButton_salaestudo_voltar.setFlat(False)

        self.horizontalLayout_3.addWidget(self.pushButton_salaestudo_voltar)

        self.label_33 = QLabel(self.gridFrame)
        self.label_33.setObjectName(u"label_33")
        font3 = QFont()
        font3.setFamilies([u"Versa"])
        font3.setPointSize(24)
        font3.setBold(False)
        font3.setItalic(False)
        self.label_33.setFont(font3)
        self.label_33.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_33)

        self.horizontalFrame_3 = QFrame(Widget)
        self.horizontalFrame_3.setObjectName(u"horizontalFrame_3")
        self.horizontalFrame_3.setGeometry(QRect(10, 80, 731, 51))
        self.horizontalFrame_3.setFrameShape(QFrame.Box)
        self.horizontalFrame_3.setFrameShadow(QFrame.Sunken)
        self.horizontalLayout_12 = QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.subtitle_environments_meeting = QLabel(self.horizontalFrame_3)
        self.subtitle_environments_meeting.setObjectName(u"subtitle_environments_meeting")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.subtitle_environments_meeting.sizePolicy().hasHeightForWidth())
        self.subtitle_environments_meeting.setSizePolicy(sizePolicy1)
        self.subtitle_environments_meeting.setMaximumSize(QSize(16777215, 25))
        font4 = QFont()
        font4.setFamilies([u"Versa Versa"])
        font4.setPointSize(18)
        self.subtitle_environments_meeting.setFont(font4)
        self.subtitle_environments_meeting.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_12.addWidget(self.subtitle_environments_meeting)

        self.pushButton_adicionar_salaestudo = QPushButton(self.horizontalFrame_3)
        self.pushButton_adicionar_salaestudo.setObjectName(u"pushButton_adicionar_salaestudo")
        sizePolicy.setHeightForWidth(self.pushButton_adicionar_salaestudo.sizePolicy().hasHeightForWidth())
        self.pushButton_adicionar_salaestudo.setSizePolicy(sizePolicy)
        self.pushButton_adicionar_salaestudo.setMaximumSize(QSize(25, 25))
        self.pushButton_adicionar_salaestudo.setFont(font4)
        icon1 = QIcon()
        iconThemeName = u"list-add"
        if QIcon.hasThemeIcon(iconThemeName):
            icon1 = QIcon.fromTheme(iconThemeName)
        else:
            icon1.addFile(u"../../ambientes", QSize(), QIcon.Normal, QIcon.Off)

        self.pushButton_adicionar_salaestudo.setIcon(icon1)
        self.pushButton_adicionar_salaestudo.setAutoDefault(False)
        self.pushButton_adicionar_salaestudo.setFlat(False)

        self.horizontalLayout_12.addWidget(self.pushButton_adicionar_salaestudo)

        self.label_13 = QLabel(self.horizontalFrame_3)
        self.label_13.setObjectName(u"label_13")
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)

        self.horizontalLayout_12.addWidget(self.label_13)


        self.retranslateUi(Widget)

        self.pushButton_adicionar_salaestudo.setDefault(False)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.footer_icon_facebook.setText("")
        self.footer_icon_likedin.setText("")
        self.footer_icon_git.setText("")
        self.subtitle_class_meeting_02.setText(QCoreApplication.translate("Widget", u"Sala 02", None))
        self.pushButton_reserve_class_meeting_02.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_02.setText(QCoreApplication.translate("Widget", u"exluir", None))
        self.pushButton_edit_class_meeting_02.setText(QCoreApplication.translate("Widget", u"editar ", None))
        self.label_description_class_meeting_02.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_sl_pipa.setText(QCoreApplication.translate("Widget", u"sala 03", None))
        self.pushButton_reserve_class_meeting_03.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_03.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_03.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_03.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_class_meeting_01.setText(QCoreApplication.translate("Widget", u"Sala 01", None))
        self.pushButton_reserve_class_meeting_01.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_01.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_01.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_01.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.subtitle_class_meeting_04.setText(QCoreApplication.translate("Widget", u"sala 04", None))
        self.pushButton_reserve_class_meeting_04.setText(QCoreApplication.translate("Widget", u"reservar", None))
        self.pushButton_delete_class_meeting_04.setText(QCoreApplication.translate("Widget", u"excluir", None))
        self.pushButton_edit_class_meeting_04.setText(QCoreApplication.translate("Widget", u"editar", None))
        self.label_description_class_meeting_04.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:11pt;\">DESCRI\u00c7\u00c3O</span></p></body></html>", None))
        self.pushButton_salaestudo_voltar.setText(QCoreApplication.translate("Widget", u"voltar", None))
        self.label_33.setText(QCoreApplication.translate("Widget", u"                           SICOGES", None))
        self.subtitle_environments_meeting.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\">        SALA DE ESTUDO</p></body></html>", None))
        self.pushButton_adicionar_salaestudo.setText(QCoreApplication.translate("Widget", u"+", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Adicionar Nova Sala", None))
    # retranslateUi

